"""Add background_jobs

Revision ID: 606ea3bcb9fe
Revises: 2da04570e5e7
Create Date: 2026-08-31 23:10:03.724998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '606ea3bcb9fe'
down_revision: Union[str, None] = '2da04570e5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
