/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyWorkRouteImport } from './routes/my-work'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdActivityRouteImport } from './routes/projects.$projectId.activity'
import { Route as ProjectsProjectIdBoardRouteImport } from './routes/projects.$projectId.board'
import { Route as ProjectsProjectIdHierarchyRouteImport } from './routes/projects.$projectId.hierarchy'
import { Route as ProjectsProjectIdStoriesRouteImport } from './routes/projects.$projectId.stories'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWorkRoute = MyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdActivityRoute =
  ProjectsProjectIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdBoardRoute = ProjectsProjectIdBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdHierarchyRoute =
  ProjectsProjectIdHierarchyRouteImport.update({
    id: '/hierarchy',
    path: '/hierarchy',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdStoriesRoute =
  ProjectsProjectIdStoriesRouteImport.update({
    id: '/stories',
    path: '/stories',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/my-work': typeof MyWorkRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/activity': typeof ProjectsProjectIdActivityRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/hierarchy': typeof ProjectsProjectIdHierarchyRoute
  '/projects/$projectId/stories': typeof ProjectsProjectIdStoriesRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/my-work': typeof MyWorkRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/activity': typeof ProjectsProjectIdActivityRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/hierarchy': typeof ProjectsProjectIdHierarchyRoute
  '/projects/$projectId/stories': typeof ProjectsProjectIdStoriesRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/my-work': typeof MyWorkRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/activity': typeof ProjectsProjectIdActivityRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/hierarchy': typeof ProjectsProjectIdHierarchyRoute
  '/projects/$projectId/stories': typeof ProjectsProjectIdStoriesRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/login'
    | '/my-work'
    | '/notifications'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/activity'
    | '/projects/$projectId/board'
    | '/projects/$projectId/hierarchy'
    | '/projects/$projectId/stories'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/login'
    | '/my-work'
    | '/notifications'
    | '/settings'
    | '/projects'
    | '/projects/$projectId/activity'
    | '/projects/$projectId/board'
    | '/projects/$projectId/hierarchy'
    | '/projects/$projectId/stories'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/login'
    | '/my-work'
    | '/notifications'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/activity'
    | '/projects/$projectId/board'
    | '/projects/$projectId/hierarchy'
    | '/projects/$projectId/stories'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  LoginRoute: typeof LoginRoute
  MyWorkRoute: typeof MyWorkRoute
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-work': {
      id: '/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof MyWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/activity': {
      id: '/projects/$projectId/activity'
      path: '/activity'
      fullPath: '/projects/$projectId/activity'
      preLoaderRoute: typeof ProjectsProjectIdActivityRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/board': {
      id: '/projects/$projectId/board'
      path: '/board'
      fullPath: '/projects/$projectId/board'
      preLoaderRoute: typeof ProjectsProjectIdBoardRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/hierarchy': {
      id: '/projects/$projectId/hierarchy'
      path: '/hierarchy'
      fullPath: '/projects/$projectId/hierarchy'
      preLoaderRoute: typeof ProjectsProjectIdHierarchyRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/stories': {
      id: '/projects/$projectId/stories'
      path: '/stories'
      fullPath: '/projects/$projectId/stories'
      preLoaderRoute: typeof ProjectsProjectIdStoriesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdActivityRoute: typeof ProjectsProjectIdActivityRoute
  ProjectsProjectIdBoardRoute: typeof ProjectsProjectIdBoardRoute
  ProjectsProjectIdHierarchyRoute: typeof ProjectsProjectIdHierarchyRoute
  ProjectsProjectIdStoriesRoute: typeof ProjectsProjectIdStoriesRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdActivityRoute: ProjectsProjectIdActivityRoute,
  ProjectsProjectIdBoardRoute: ProjectsProjectIdBoardRoute,
  ProjectsProjectIdHierarchyRoute: ProjectsProjectIdHierarchyRoute,
  ProjectsProjectIdStoriesRoute: ProjectsProjectIdStoriesRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  LoginRoute: LoginRoute,
  MyWorkRoute: MyWorkRoute,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
